### ISSUE TITLE
File "built.py", line 126, in embed_accounts; TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Atilla31s** [addi00000/empyrean#1]
Traceback (most recent call last):
  File "built.py", line 605, in <module>
  File "built.py", line 33, in main
  File "built.py", line 66, in __init__
  File "built.py", line 126, in embed_accounts
TypeError: string indices must be integers

**Comment by mte0** [comment]
https://github.com/addi00000/empyrean/commit/a303fa80e47949e7c15304f66abe96aeef22422d

**Comment by addi00000** [comment]
Not fixed
