### ISSUE TITLE
[BUG] When I try to build EXE it gives me error as below.

### ISSUE THREAD

**Issue by heqds** [addi00000/empyrean#129]
**Describe the bug**
The error below is popping up when I try to build exe

**To Reproduce**
Prob just me

**Expected behavior**
Build exe

**Error:**

Traceback (most recent call last):
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Scripts\pyinstaller-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyinstaller==5.1', 'console_scripts', 'pyinstaller')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\__main__.py", line 159, in run
    parser = generate_parser()
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\__main__.py", line 126, in generate_parser
    import PyInstaller.building.build_main
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\building\build_main.py", line 27, in <module>
    from PyInstaller.building.api import COLLECT, EXE, MERGE, PYZ
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\building\api.py", line 27, in <module>
    from PyInstaller.archive.writers import CArchiveWriter, ZlibArchiveWriter
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\archive\writers.py", line 28, in <module>
    from PyInstaller.building.utils import fake_pyc_timestamp, get_code_object, strip_paths_in_code
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\building\utils.py", line 31, in <module>
    from PyInstaller.depend.bindepend import match_binding_redirect
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\depend\bindepend.py", line 26, in <module>
    from PyInstaller.depend import dylib, utils
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\depend\utils.py", line 29, in <module>
    from PyInstaller.depend import bytecode
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\depend\bytecode.py", line 85, in <module>
    _call_function_bytecode = bytecode_regex(
                              ^^^^^^^^^^^^^^^
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\depend\bytecode.py", line 52, in bytecode_regex
    pattern = re.sub(
              ^^^^^^^
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\depend\bytecode.py", line 54, in <lambda>
    lambda m: _instruction_to_regex(m[1].decode()),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\heqds\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyinstaller-5.1-py3.11.egg\PyInstaller\depend\bytecode.py", line 35, in _instruction_to_regex
    return re.escape(bytes([dis.opmap[x]]))
                            ~~~~~~~~~^^^
KeyError: 'CALL_FUNCTION'
Press any key to continue . . .

**Comment by KDot227** [comment]
Don’t use 3.11 @heqds

**Comment by addi00000** [comment]
Uninstall python 3.11
Install python 3.10
