### ISSUE TITLE
[BUG] i am getting this error

### ISSUE THREAD

**Issue by Louis-Beke** [addi00000/empyrean#132]
this is in build.bat

HEAD is now at 4173bd1 create API, add doc on it
[15:22:40] {                                                                                                  main.py:81               'general.input_file': 'input.py',
               'general.output_file': 'output.py',
               'general.transitive': True,
               'general.manual_include': [],
               'general.overwrite_output_forcefully': False,
               'removeTypeHints.enabled': False,
               'fstrToFormatSeq.enabled': False,
               'intObfuscator.enabled': False,
               'intObfuscator.mode': 'bits',
               'encodeStrings.enabled': False,
               'renamer.enabled': False,
               'renamer.rename_format': "f'{kind}{get_counter(kind)}'",
               'replaceAttribSet.enabled': False,
               'unicodeTransformer.enabled': False,
               'dynamicCodeObjLauncher.enabled': False,
               'varCollector.enabled': False,
               'compileFinalFiles.enabled': False,
               'packInPyz.enabled': False,
               'packInPyz.bootstrap_file': '__main__.py'
           }
           Parsing inheritance tree...                                                                       main.py:158           main.py                                                                                           main.py:170           ├── components\antidebug.py
           ├── components\browsers.py
           ├── components\discordtoken.py
           ├── components\injection.py
           ├── components\startup.py
           ├── components\systeminfo.py
           └── config.py
                   main.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformer   components\antidebug.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformer    components\browsers.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformercomponents\discordtoken.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformer   components\injection.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformer     components\startup.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformer  components\systeminfo.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformer                 config.py ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 75.0% •   Transformer unicodeTransformerTraceback (most recent call last):
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\main.py", line 24, in <module>
    launch()
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\main.py", line 9, in launch
    main.main()
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\obfuscator\main.py", line 103, in main
    go_transitive()
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\obfuscator\main.py", line 212, in go_transitive
    for processed_file in do_obfuscation_batch_ast(all_asts, all_files):
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\obfuscator\__init__.py", line 105, in do_obfuscation_batch_ast
    source_asts[i] = fix_missing_locations(x.transform(s_ast, s_fn, source_asts, source_file_names))
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\obfuscator\transformers\collector.py", line 132, in transform
    trafod_ast.body.insert(0, self.create_loader())
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\obfuscator\transformers\collector.py", line 114, in create_loader
    co = self._create_co_obj()
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\obfuscator\transformers\collector.py", line 80, in _create_co_obj
    class_ctor.insn("resume", 0)
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\build\pyobf2\obfuscator\assembler.py", line 129, in insn
    raise ValueError("Unknown insn " + name)
ValueError: Unknown insn RESUME
Traceback (most recent call last):
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\builder.py", line 212, in <module>
    main()
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\builder.py", line 206, in main
    build.get_pyinstaller()
  File "C:\Users\louis\Downloads\empyrean-main\empyrean-main\builder.py", line 168, in get_pyinstaller
    subprocess.run(['unzip', 'pyinstaller.zip'], cwd=self.build_dir)
  File "C:\Users\louis\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\louis\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\louis\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Press any key to continue . . .

**Comment by Louis-Beke** [comment]
ooh

**Comment by Louis-Beke** [comment]
3.10

**Comment by Louis-Beke** [comment]
by when would it be fixed

**Comment by Louis-Beke** [comment]
i am not getting the password

**Comment by Louis-Beke** [comment]
@addi00000
