### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gerson7002** [addi00000/empyrean#178]
**When build | Error ( traceback most recent call last): **
when I want to build it it will do something but then suddenly it says (see the error below).

Traceback (most recent call last):
  File "C:\Users\gerso_j1idd9v\Downloads\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\gerso_j1idd9v\Downloads\empyrean-main\builder.py", line 247, in main
    build.build()
  File "C:\Users\gerso_j1idd9v\Downloads\empyrean-main\builder.py", line 208, in build
    subprocess.run(['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', self.dist_dir, '--workpath', os.path.join(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden
Press any key to continue . . .

**To Reproduce**
1. execute build.bat
2. press 5/6 times y to say yes
3. wait  and see the error

**Expected behavior**
i thought he would, and something came up in discord

![Schermafbeelding 2023-02-22 121324](https://user-images.githubusercontent.com/126071867/220604026-ffe44c4b-a749-486e-aa50-e635012272c1.png)

**Comment by pumpkinsob** [comment]
need help
