### ISSUE TITLE
[BUG] How to use

### ISSUE THREAD

**Issue by A1m4Life** [addi00000/empyrean#179]
If i open the main.exe file i just grab myself, do i have to send the file to people i want to grab or is there another way?

**Comment by louis0623** [comment]
yes and can you tell me how can fix the error that happening on everytime i done the setting and it wont work?
Traceback (most recent call last):
  File "C:\Users\dear6\Videos\empyrean-main (1)\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\dear6\Videos\empyrean-main (1)\empyrean-main\builder.py", line 247, in main
    build.build()
  File "C:\Users\dear6\Videos\empyrean-main (1)\empyrean-main\builder.py", line 208, in build
    subprocess.run(['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', self.dist_dir, '--workpath', os.path.join(
  File "C:\Users\dear6\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\dear6\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dear6\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]
like this

**Comment by Saymizan** [comment]
Same for me whenever i run main.exe in grabs myself, shld i sent this to the person i wanna grab? also it does not send the vault to my discord it sends it to the file dist. please help asap

**Comment by Saymizan** [comment]
also the main.exe deletes it self after grabbing my self....

**Comment by crispyrice526** [comment]
> Same for me whenever i run main.exe in grabs myself, shld i sent this to the person i wanna grab? also it does not send the vault to my discord it sends it to the file dist. please help asap
You need to send this to the victim you are attempting to rat. In order to receive the victims info you must set up discord server and create a webhook. Paste the webhook into the config file and replace the word 'None' in 'webhook' : None,
