### ISSUE TITLE
[BUG] Doesn't Work

### ISSUE THREAD

**Issue by ghost** [addi00000/empyrean#181]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "components\antidebug.py", line 7, in <module>
ModuleNotFoundError: No module named 'requests'

**Comment by ar4969371** [comment]
`pip install requests`

Could've googled this.

**Comment by Wizz1337** [comment]
make sure to do `pip install -r requirements.txt`
