### ISSUE TITLE
[BUG] Error Code 

### ISSUE THREAD

**Issue by Jaydxn133** [addi00000/empyrean#190]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\User\Downloads\empyrean-main\builder.py", line 229, in main
    make_env.make_env()
  File "C:\Users\User\Downloads\empyrean-main\builder.py", line 89, in make_env
    shutil.rmtree(self.build_dir)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\User\\Downloads\\empyrean-main\\build\\empyrean\\.git\\objects\\pack\\pack-4488591d88987c6ae4d9719fbd35242355095c2b.idx'

**Comment by MrBacon1-1** [comment]
Goto the folder and delete dist and the folder above it only leave src I have no idea why this happens
