### ISSUE TITLE
[BUG] Cant build, This getting an error

### ISSUE THREAD

**Issue by 42FortyTwo** [addi00000/empyrean#207]
This is the message i am getting when trying to build it
I use win 10

Traceback (most recent call last):
  File "C:\Users\Pc\Desktop\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\Pc\Desktop\empyrean-main\builder.py", line 247, in main
    build.build()
  File "C:\Users\Pc\Desktop\empyrean-main\builder.py", line 208, in build
    subprocess.run(['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', self.dist_dir, '--workpath', os.path.join(
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\Pc>

**Comment by 42FortyTwo** [comment]
I did but I am getting new error now 
  File "C:\Users\Pc\Desktop\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\Pc\Desktop\empyrean-main\builder.py", line 229, in main
    make_env.make_env()
  File "C:\Users\Pc\Desktop\empyrean-main\builder.py", line 89, in make_env
    shutil.rmtree(self.build_dir)
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Pc\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Pc\\build\\empyrean\\.git\\objects\\pack\\pack-bb0406526a51e7209c5527efe4f37e0ebf6cc2fb.idx'

**Comment by Lunarhub-V3** [comment]
Try downloading git?
