### ISSUE TITLE
Traceback (most recent call last):   File "main.py", line 2, in <module>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module   File "components\browsers.py", line 9, in <module> ImportError: cannot import name 'Embed' from 'discord' (unknown location)[BUG]

### ISSUE THREAD

**Issue by tbpuk1** [addi00000/empyrean#232]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "components\browsers.py", line 9, in <module>
ImportError: cannot import name 'Embed' from 'discord' (unknown location)

**Comment by Doridori9992** [comment]
Having same problem

**Comment by Bossmaster45** [comment]
same
