### ISSUE TITLE
[SOLVED] Error after putting in webhook and other stuff

### ISSUE THREAD

**Issue by Naahhmate** [addi00000/empyrean#242]
Traceback (most recent call last):
  File "C:\Users\naahh\Downloads\empyrean-main\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\naahh\Downloads\empyrean-main\empyrean-main\builder.py", line 229, in main
    make_env.make_env()
  File "C:\Users\naahh\Downloads\empyrean-main\empyrean-main\builder.py", line 89, in make_env
    shutil.rmtree(self.build_dir)
  File "C:\Users\naahh\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\naahh\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\naahh\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\naahh\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Users\naahh\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\naahh\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\naahh\\Downloads\\empyrean-main\\empyrean-main\\build\\empyrean\\.git\\objects\\pack\\pack-5042b3e00a8d12f71dcda92af553425517e3a7ab.idx'

**Comment by Misterpopcorn12** [comment]
how did u fix it tho
