### ISSUE TITLE
[BUG]bulid bug after putting webhooks

### ISSUE THREAD

**Issue by tantanjoy11** [addi00000/empyrean#243]
Traceback (most recent call last):
  File "D:\empyrean-main\builder.py", line 254, in <module>
    main()
  File "D:\empyrean-main\builder.py", line 247, in main
    build.build()
  File "D:\empyrean-main\builder.py", line 208, in build
    subprocess.run(['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', self.dist_dir, '--workpath', os.path.join(
  File "C:\Users\tantan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\tantan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\tantan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Press any key to continue . . .
![image](https://user-images.githubusercontent.com/130871044/232254734-cef12e1d-23c4-41ba-9fb7-d8cd1cf2e997.png)

**Comment by MrRaphi** [comment]
reinstall python by the command file atleast it worked for me
