### ISSUE TITLE
[BUG "FileNotFoundError: [WinError 2] The system cannot find the file specified"]

### ISSUE THREAD

**Issue by duddjddfitv** [addi00000/empyrean#257]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\User\Downloads\empyrean-main\builder.py", line 247, in main
    build.build()
  File "C:\Users\User\Downloads\empyrean-main\builder.py", line 208, in build
    subprocess.run(['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', self.dist_dir, '--workpath', os.path.join(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by duddjddfitv** [comment]
help

**Comment by zephr1213** [comment]
SAME ISSUE

**Comment by zephr1213** [comment]
Traceback (most recent call last):
  File "C:\Users\kidsa\Downloads\empyrean-main\empyrean-main\builder.py", line 254, in <module>
    main()
  File "C:\Users\kidsa\Downloads\empyrean-main\empyrean-main\builder.py", line 247, in main
    build.build()
  File "C:\Users\kidsa\Downloads\empyrean-main\empyrean-main\builder.py", line 208, in build
    subprocess.run(['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', self.dist_dir, '--workpath', os.path.join(
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
