### ISSUE TITLE
[BUG] [WinError 3] The system cannot find the path specified.

### ISSUE THREAD

**Issue by Arden803** [addi00000/empyrean#265]
**Describe the bug**
Getting error 

FileNotFoundError: WinError 31 The system cannot find the path specified:
'C: I Windows\System32\\src'

**Screenshots**
<img width="1680" alt="Screenshot 2023-05-11 at 10 59 27" src="https://github.com/addi00000/empyrean/assets/131528943/24bc03cb-7420-4e23-b368-a02635f52833">

**Additional context**
I ran build.bat as administrator and same problem

**Comment by addi00000** [comment]
dont run elevated
just double click and run as user in cwd

**Comment by Arden803** [comment]
> dont run elevated just double click and run as user in cwd

when i run as user it just gives this

Traceback (most recent call last):
  File "\\Mac\Home\Downloads\empyrean-main (3)\empyrean-main\builder\main.py", line 58, in <module>
    main()
  File "\\Mac\Home\Downloads\empyrean-main (3)\empyrean-main\builder\main.py", line 42, in main
    make_env.make_env()
  File "\\Mac\Home\Downloads\empyrean-main (3)\empyrean-main\builder\util\makeenv.py", line 20, in make_env
    os.mkdir(self.build_dir)
PermissionError: [WinError 5] Access is denied: 'C:\\Windows\\build'
