### ISSUE TITLE
help me with this problem

### ISSUE THREAD

**Issue by zerowaree** [addi00000/empyrean#285]
legraph\modulegraph.py", line 2645, in _scan_code
    self._scan_bytecode(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2749, in _scan_bytecode
    for inst in util.iterate_instructions(module_code_object):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\lib\modulegraph\util.py", line 139, in iterate_instructions
    yield from get_instructions(code_object)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\dis.py", line 338, in _get_instructions_bytes
    argval, argrepr = _get_const_info(arg, constants)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\dis.py", line 292, in _get_const_info
    argval = const_list[const_index]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "C:\Users\User\Documents\empyrean-main\builder\main.py", line 58, in <module>
    main()
  File "C:\Users\User\Documents\empyrean-main\builder\main.py", line 54, in main
    build.build()
  File "C:\Users\User\Documents\empyrean-main\builder\util\build.py", line 56, in build
    subprocess.run([
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', 'C:\\Users\\User\\Documents\\empyrean-main\\build\\..\\dist', '--workpath', 'C:\\Users\\User\\Documents\\empyrean-main\\build/work', '--specpath', 'C:\\Users\\User\\Documents\\empyrean-main\\build/spec', '--upx-dir', 'C:\\Users\\User\\Documents\\empyrean-main\\build/upx-3.96-win64', 'C:\\Users\\User\\Documents\\empyrean-main\\build/src/main.py']' returned non-zero exit status 1.

**Comment by zerowaree** [comment]
no xd
