### ISSUE TITLE
"cannot import name 'Embed' from 'discord' (unknown location)"[BUG]

### ISSUE THREAD

**Issue by Claym64** [addi00000/empyrean#334]
Installed requirements (on python 1.10.9) and builded exe file, after i open it to check it gives me error: 

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "components\browsers.py", line 10, in <module>
ImportError: cannot import name 'Embed' from 'discord' (unknown location)
```
![image](https://github.com/addi00000/empyrean/assets/130917945/e01816fb-4759-4584-86b1-974bf41deb4d)

**Comment by sag4ev** [comment]
how to solve that?
