### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aysenazemirhan** [addi00000/empyrean#42]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "util\chromium.py", line 9, in <module>
ModuleNotFoundError: No module named 'Crypto'

**Comment by addi00000** [comment]
Closing. If the issue prevails, please make a new issue and elaborate, provide screenshots, etc. for me to better assist you
