### ISSUE TITLE
[BUG] invalid syntax

### ISSUE THREAD

**Issue by real-fbdn** [addi00000/empyrean#427]
SyntaxError: invalid syntax
31865 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__init__.py", line 17, in <module>
    from PyInstaller import compat
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\compat.py", line 199, in <module>
    from win32ctypes.pywin32 import pywintypes  # noqa: F401, E402
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\pywin32\__init__.py", line 9, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\pywin32\win32api.py", line 9, in <module>
    from win32ctypes.core import (
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\core\__init__.py", line 30, in load_module
    module = importlib.import_module(self.redirect_module)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\core\cffi\__init__.py", line 8, in <module>
    import logging
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\logging\__init__.py", line 618
    raise NotImplementedError, 'emit must be implemented '\
                             ^
SyntaxError: invalid syntax
32095 INFO: Loading module hook 'hook-win32com.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
32181 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32185 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32185 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32191 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32261 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32265 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32306 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32309 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32384 INFO: Import to be excluded not found: 'f2py'
32394 INFO: Loading module hook 'hook-numpy._pytesttester.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32397 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32398 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32405 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32892 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32896 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32915 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
32918 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
34471 WARNING: Hidden import "pkg_resources.py2_warn" not found!
34477 WARNING: Hidden import "pkg_resources.markers" not found!
34482 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
34487 INFO: Loading module hook 'hook-pygments.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
36812 INFO: Loading module hook 'hook-scipy.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
36818 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38416 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38509 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38514 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38883 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38884 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38885 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38885 INFO: Loading module hook 'hook-zope.interface.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
38891 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
39065 INFO: checking Tree
39066 INFO: Building Tree because Tree-00.toc is non existent
39066 INFO: Building Tree Tree-00.toc
39158 INFO: checking Tree
39159 INFO: Building Tree because Tree-01.toc is non existent
39159 INFO: Building Tree Tree-01.toc
39247 INFO: checking Tree
39247 INFO: Building Tree because Tree-02.toc is non existent
39247 INFO: Building Tree Tree-02.toc
39255 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
39257 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
39374 INFO: Looking for ctypes DLLs
39476 INFO: Analyzing run-time hooks ...
39489 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
39490 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
39492 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
39502 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
39506 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
39510 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
39511 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pywintypes.py'
39512 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
39513 INFO: Including run-time hook 'C:\\Users\\ayaan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pythoncom.py'
39559 INFO: Looking for dynamic libraries
C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py:156: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
2143 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\bootloader\waflib\Tools\cs.py
2143 WARNING:   Reason: 'DOS Header magic not found.'
2144 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-PIL.Image.py
2144 WARNING:   Reason: 'DOS Header magic not found.'
2145 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\bootloader\waflib\Tools\ldc2.py
2145 WARNING:   Reason: 'DOS Header magic not found.'
2146 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\functional\modules\pkg3\__init__.py
2146 WARNING:   Reason: 'Unable to read the DOS Header, possibly a truncated file.'
2147 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\unit\test_modulegraph\testpkg-regr7\script.py
2147 WARNING:   Reason: 'Unable to read the DOS Header, possibly a truncated file.'
2148 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\functional\modules\pyi_testmod_nameclash\nameclash.py
2148 WARNING:   Reason: 'Unable to read the DOS Header, possibly a truncated file.'
2149 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-PyQt6.QtHelp.py
2149 WARNING:   Reason: 'DOS Header magic not found.'
2150 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\functional\test_interactive.py
2150 WARNING:   Reason: 'DOS Header magic not found.'
2151 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\build\lib\PyInstaller\loader\pyimod02_archive.py
2151 WARNING:   Reason: 'DOS Header magic not found.'
2151 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-scipy.io.matlab.py
2151 WARNING:   Reason: 'DOS Header magic not found.'
2152 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\build\lib\PyInstaller\hooks\hook-packaging.py
2152 WARNING:   Reason: 'DOS Header magic not found.'
2154 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-PIL.SpiderImagePlugin.py
2154 WARNING:   Reason: 'DOS Header magic not found.'
2155 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-PySide2.QtHelp.py
2155 WARNING:   Reason: 'DOS Header magic not found.'
2156 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\unit\test_modulegraph\testpkg-edgedata\toplevel_existing.py
2156 WARNING:   Reason: 'Unable to read the DOS Header, possibly a truncated file.'
2158 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\unit\test_modulegraph\testpkg-packages\pkg\sub3.py
2158 WARNING:   Reason: 'Unable to read the DOS Header, possibly a truncated file.'
2159 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-multiprocessing.util.py
2160 WARNING:   Reason: 'DOS Header magic not found.'
2161 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-win32ctypes.core.py
2161 WARNING:   Reason: 'DOS Header magic not found.'
2162 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\bootloader\waflib\Tools\fc.py
2163 WARNING:   Reason: 'DOS Header magic not found.'
2163 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\unit\test_modulegraph\testdata\nspkg\setuptools-28.1.0\parent\namedpkg\parent.py
2164 WARNING:   Reason: 'Unable to read the DOS Header, possibly a truncated file.'
2164 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\doc\license.rst
2164 WARNING:   Reason: 'DOS Header magic not found.'
2165 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\bootloader\zlib\inffast.h
2165 WARNING:   Reason: 'DOS Header magic not found.'
2166 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\functional\logs\test_nspkg3_bbb_zzz.toc
2166 WARNING:   Reason: 'Unable to read the DOS Header, possibly a truncated file.'
2167 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\tests\unit\conftest.py
2167 WARNING:   Reason: 'DOS Header magic not found.'
2167 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\build\lib\PyInstaller\hooks\pre_find_module_path\hook-PyQt5.uic.port_v2.py
2167 WARNING:   Reason: 'DOS Header magic not found.'
2168 WARNING: Cannot get binary dependencies for file: build\pyinstaller-5.1\PyInstaller\hooks\hook-pkg_resources.py
2168 WARNING:   Reason: 'DOS Header magic not found.'
Traceback (most recent call last):
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>    sys.exit(run())
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "C:\Users\ayaan\OneDrive\Desktop\Empyrean\build/spec\main.spec", line 7, in <module>
    a = Analysis(
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 319, in __init__
    self.__postinit__()
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 546, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 238, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 176, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to find_binary_dependencies() failed with:
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\pywin32\win32api.py", line 40, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\core\cffi\_dll.py", line 20, in _LoadLibraryEx
    result = check_null(
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\core\cffi\_util.py", line 78, in __call__
    self._raise_error(function_name)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\core\cffi\_util.py", line 89, in _raise_error
    raise exception
OSError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 161, in find_binary_dependencies
    return bindepend.Dependencies(binaries, redirects=binding_redirects, xtrapath=extra_libdirs)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\bindepend.py", line 205, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\bindepend.py", line 372, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\bindepend.py", line 326, in getAssemblies
    res = winmanifest.GetManifestResources(pth)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 980, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 155, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\pywin32\win32api.py", line 39, in LoadLibraryEx
    with _pywin32error():
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (2, 'LoadLibraryEx', 'The system cannot find the file specified')
Traceback (most recent call last):
  File "C:\Users\ayaan\OneDrive\Desktop\Empyrean\builder\main.py", line 58, in <module>
    main()
  File "C:\Users\ayaan\OneDrive\Desktop\Empyrean\builder\main.py", line 54, in main
    build.build()
  File "C:\Users\ayaan\OneDrive\Desktop\Empyrean\builder\util\build.py", line 56, in build
    subprocess.run([
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyinstaller', '--onefile', '--noconsole', '--clean', '--distpath', 'C:\\Users\\ayaan\\OneDrive\\Desktop\\Empyrean\\build\\..\\dist', '--workpath', 'C:\\Users\\ayaan\\OneDrive\\Desktop\\Empyrean\\build/work', '--specpath', 'C:\\Users\\ayaan\\OneDrive\\Desktop\\Empyrean\\build/spec', '--upx-dir', 'C:\\Users\\ayaan\\OneDrive\\Desktop\\Empyrean\\build/upx-3.96-win64', 'C:\\Users\\ayaan\\OneDrive\\Desktop\\Empyrean\\build/src/main.py']' returned non-zero exit status 1.
Press any key to continue . . .

**Comment by zzlyz** [comment]
yes i get this issue too :/
