### ISSUE TITLE
[BUG]Traceback (most recent call last):   File "main.py", line 6, in <module> ModuleNotFoundError: No module named 'components.browsers'

### ISSUE THREAD

**Issue by RyZeBLAZE** [addi00000/empyrean#450]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
ModuleNotFoundError: No module named 'components.browsers'

**Comment by Oronno03** [comment]
Try this to fix it:

1. Download this [file](https://github.com/addi00000/empyrean/blob/main/src/components/browsers.py) and put it in the src/components folder in your empyrean directory.
![image](https://github.com/addi00000/empyrean/assets/143703231/85ab9933-f079-4145-a982-e7eeced153db)

OR

1. In the src/components folder create a file called "browsers.py"

2. Copy and paste the content from this [file](https://github.com/addi00000/empyrean/blob/main/src/components/browsers.py) from the repository to the browsers.py  just created.

Build it again and it should work fine now.
