### ISSUE TITLE
[BUG] Again a weird error.

### ISSUE THREAD

**Issue by zappelig** [addi00000/empyrean#46]
Hey addi, some days ago I posted another weird error and you closed it as completed. I don't remember if this is the same error but I would like it if you fix this. (I don't really know if someone already reported that, sorry...)

Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<string>", line 38, in <module>
  File "<string>", line 27, in main
  File "<string>", line 36, in __init__
  File "<string>", line 153, in network_data
  File "<string>", line 139, in proxy_check
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

And also I would like to suggest an AntiVM and Icon option.

**Comment by zrexvc** [comment]
![Immagine_2022-09-29_171241](https://user-images.githubusercontent.com/96620548/193070492-d53c9b3c-c281-4544-a789-94ca771ebdc0.png)
And another weird error... I guess not so good if my victim knows that ge just got grabbed...
