### ISSUE TITLE
when i open main file it says failed to execute script main.

### ISSUE THREAD

**Issue by ummix** [addi00000/empyrean#460]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "components\browsers.py", line 10, in <module>
ImportError: cannot import name 'Embed' from 'discord' (unknown location)
![image](https://github.com/addi00000/empyrean/assets/163020589/710bfe64-2b72-42a8-bbf8-49747183c190)

**Comment by ARfefe** [comment]
how did you do it please ?

**Comment by raiseeee** [comment]
fixed?
