### ISSUE TITLE
[BUG] FileNotFoundError

### ISSUE THREAD

**Issue by veskymak** [addi00000/empyrean#83]
**Describe the bug**

**To Reproduce**
1. Go to 'build.bat'
2. Fill out "yes" or "no"
3. After all above done error pops up

**Expected behavior**
The building of the executable.

**Screenshots**
![image](https://user-images.githubusercontent.com/115838468/203644258-da393aa2-91e0-443e-9a06-54c424135b69.png)

**Additional context**
Windows 11

Error:
Traceback (most recent call last):
  File "C:\Users\vacla\Downloads\empyrean-main\empyrean-main\builder.py", line 132, in <module>
    main()
  File "C:\Users\vacla\Downloads\empyrean-main\empyrean-main\builder.py", line 127, in main
    make_env()()
  File "C:\Users\vacla\Downloads\empyrean-main\empyrean-main\builder.py", line 64, in __call__
    self.get_src()
  File "C:\Users\vacla\Downloads\empyrean-main\empyrean-main\builder.py", line 73, in get_src
    subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir)
  File "C:\Users\vacla\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\vacla\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\vacla\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System cannot find the specified file
Press any key to continue . . .

**Comment by addi00000** [comment]
You need to install [Git](https://git-scm.com/download/win) as stated in the prerequisites.
